export const SET_QUERY = 'set query'
export const NEXT_PAGE = 'next page'
export const PREV_PAGE = 'prev page'
export const FETCH_GIFS_REQUEST = 'fetch gifs request'
export const FETCH_GIFS_SUCCESS = 'fetch gifs success'
export const FETCH_GIFS_FAILURE = 'fetch gifs failure'
export const SEARCH_GIPHY = 'search giphy'
